import AddressModel from '../models/address';
import AuditModel from '../models/audit';
import AuthModel from '../models/auth';
import BlacklistedTokenModel from '../models/black-listed-token';
import BrancheModel from '../models/branche';
import CategoryModel from '../models/category';
import ClientModel from '../models/client';
import ComplaintsSuggestionModel from '../models/complaints-suggestion';
import InboxModel from '../models/inbox';
import InvoiceMenuModel from '../models/invoice-menu';
import InvoiceModel from '../models/invoice';
import MenuModel from '../models/menu';
import PasswordModel from '../models/password';
import PaymentInstrumentModel from '../models/payment-instrument';
import PaymentModel from '../models/payment';
import PlanModel from '../models/plan';
import PricingModel from '../models/pricing';
import SessionModel from '../models/session';
import ShiftModel from '../models/shift';
import SubscriptionModel from '../models/subscription';
import WebhookEventModel from '../models/webhook-event';
import { AuthRepository } from './AuthRepository';
import { BaseRepository } from './BaseRepository';
import { InvoiceRepository } from './InvoiceRepository';
import { SessionRepository } from './SessionRepository';

export const addressRepository = new BaseRepository<any>(AddressModel);
export const auditRepository = new BaseRepository<any>(AuditModel);
export const authRepository = new AuthRepository(AuthModel);
export const blacklistedTokenRepository = new BaseRepository<any>(BlacklistedTokenModel);
export const brancheRepository = new BaseRepository<any>(BrancheModel);
export const categoryRepository = new BaseRepository<any>(CategoryModel);
export const clientRepository = new BaseRepository<any>(ClientModel);
export const complaintsSuggestionRepository = new BaseRepository<any>(ComplaintsSuggestionModel);
export const inboxRepository = new BaseRepository<any>(InboxModel);
export const invoiceMenuRepository = new BaseRepository<any>(InvoiceMenuModel);
export const invoiceRepository = new InvoiceRepository(InvoiceModel);
export const menuRepository = new BaseRepository<any>(MenuModel);
export const passwordRepository = new BaseRepository<any>(PasswordModel);
export const paymentRepository = new BaseRepository<any>(PaymentModel);
export const paymentInstrumentRepository = new BaseRepository<any>(PaymentInstrumentModel);
export const planRepository = new BaseRepository<any>(PlanModel);
export const pricingRepository = new BaseRepository<any>(PricingModel);
export const sessionRepository = new SessionRepository(SessionModel);
export const shiftRepository = new BaseRepository<any>(ShiftModel);
export const subscriptionRepository = new BaseRepository<any>(SubscriptionModel);
export const webhookEventRepository = new BaseRepository<any>(WebhookEventModel);
